name: comple_workflow
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: date
  windows:
    runs-on: windows-lates
      steps:
      - run: date
  macos:
    runs-on: macos-lates
      steps:
      - run: date
  depends:
    needs: [ubuntu,windows,macos]
    runs-on:
      steps:
      - run: date
      
  
